config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'appointments#index'

  # Route will allow deletion of all expired appointments /w button click
  delete 'appointments/delete_all', to: 'appointments#destroy_all_expired'
  
  # Nested Routes for appointments inside of patients
  # /patients/:id/appointments/new
  # /patients/:id/appointments/:id/edit
  resources :patients do
    resources :appointments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :users, :through => :appointments
    accepts_nested_attributes_for :appointments
    validates :name, :presence => true,
                     :uniqueness => true,
                     :format => { with: /\D/, message: "%{value} is not valid. Must only contain letters." }
    validates :age, :presence => true

    scope :search, -> (search) { where("name LIKE ?", "%#{search}%") }

    
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_patient, only: [:show, :edit, :update, :destroy]

    def index
        if params[:search]
            @patients = Patient.search(params[:search])
        else
            @patients = Patient.all
        end
    end

    def show
        if !Patient.exists?(params[:id])
            redirect_to patients_path, alert: "Patient not found."
        else
            @appointments = @patient.appointments.order(:appointment_date)
        end
    end

    def new
        @patient = Patient.new
        @patient.appointments.build
        @appointments = Appointment.order(:appointment_date)
    end

    def create
        @patient = Patient.new(patient_params)
        @patient.appointments.last.user_id = current_user.id

        if @patient.save
            redirect_to patient_path(@patient), notice: "Patient & Appointment created sucessfully."
        else
            @appointments = Appointment.all
            render 'new'
        end
    end

    def edit
        if !Patient.exists?(params[:id])
            redirect_to patients_path, alert: "Patient not found."
        else
            @appointments = @patient.appointments.last
        end
    end


    def update
        if @patient.update(patient_params)
            redirect_to patient_path(@patient)
        else
            render 'edit'
        end
    end


    def destroy
        @patient.appointments.each do |appointment|
            if current_user.appointments.include?(appointment)
                
                appointment.destroy
            end
        end
        
        if @patient.appointments.count > 0
            redirect_to patient_path(@patient), alert: "You cannot delete this patient. It has appointments by other physicians. However, your appointments with this patient have been removed."
        else
            @patient.destroy
            redirect_to patients_path, notice: "Patient deleted sucessfully."
        end        
    end


    private
    def patient_params
        params.require(:patient).permit(:name, :age, :search,
                                        appointments_attributes:
                                        [:appointment_date])
    end

    def find_patient
        @patient = Patient.find_by(id: params[:id])
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<h3>Edit Patient</h3>
<hr class="style-two">
<%= form_for(@patient) do |f| %>
    <% if @patient.errors.any? %>
        <% @patient.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <div>
    <%= f.label :name, "Patient Name:" %>
    <%= f.text_field :name %>

    <%= f.label :age, "Patient Age:" %>
    <%= f.number_field :age %>
    </div>
    
    <div>
    <%= f.submit %>
    </div>
<% end %>

app/views/patients/index.html.erb
<h3>All Patients (<%= @patients.count %>)</h3>
<h4>Create an appointment based on a patient</h4>
<hr class="style-two">

<%# Search Form to find patients by name %>
<%# Will show any patient 'containing' the search result %>
<%= form_tag(patients_path, method: "get") do %>
  <%= label_tag(:search, "Search by Patient Name:") %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

<%# Table to show all patients %>
<table style="width:100%">
    <tr>
        <th>Patient</th>
        <th>Patient Age</th>
        <th>Next Appointment</th>
        <th>Appointment Count</th>
        <th>Patient Options</th>
    </tr>
    <% @patients.each do |patient| %>
        <% appointments = patient.appointments.order(:appointment_date) %>
    <tr>
        <td><%= link_to patient.name, patient_path(patient) %></td>
        <td><%= patient.age %> years old</td>

        <td>
        <% if patient.appointments.current.count > 0 %>
            <%# Chaining another scope method here %>
            <%= appointments.current.first.appointment_date.strftime("%m/%d/%Y %I:%M %p")%>
        <% else %>
            No Future Appointments
        <% end %>
        </td>

        <td><%= appointments.count %> Appointment(s)</td>
        <td>
            <%= link_to 'Create Appointment', new_patient_appointment_path(patient), class: "btn btn-success"%>
            <%= link_to 'View', patient_path(patient), class: "btn btn-info"%>
            <%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-warning" %>
            <%= link_to 'Delete', patient_path(patient),
                        method: :delete,
                        class: "btn btn-danger",
                        data: {confirm: 'Are you sure?'}%>
        </td>
    </tr>
    <% end %>
</table>

app/views/patients/new.html.erb
<h3>New Patient & New Appointment</h3>
<hr class="style-two">
<%= form_for(@patient) do |f| %>
    <% if @patient.errors.any? %>
        <% @patient.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

    <div>
    <%= f.label :name, "Patient Name:" %>
    <%= f.text_field :name %>

    <%= f.label :age, "Patient Age:" %>
    <%= f.number_field :age %>
    </div>

    <%= f.fields_for :appointments do |af| %>
        <p><%= af.label :appointment_date, "Appointment Date/Time:"%>
        <%= af.datetime_field :appointment_date, min: Date.today %></p>
    <% end %>
    <div>
    <%= f.submit %>
    </div>
<% end %>

<%# Form to show YOUR upcoming appointments %>
<%= render partial: 'appointments/upcoming_appt', locals: {appointments: @appointments} %>

app/views/patients/show.html.erb
<%# Patient Info and Options for patient %>
<h3><%= @patient.name %>'s Appointments (<%= @patient.age %> years old) | 
<%= link_to "Create Appointment", new_patient_appointment_path(@patient), class: "btn btn-success"%> |
<%= link_to "Edit Patient File", edit_patient_path(@patient), class: "btn btn-warning" %> |
<%= link_to 'Delete Patient', patient_path(@patient),
                        method: :delete,
                        class: "btn btn-danger",
                        data: {confirm: 'Are you sure?'}%></h3>
<hr class="style-two">

<%# Table to show patients information %>
<table width="100%">
    <tr>
        <th>Physician</th>
        <th>Appointment Date/Time</th>
        <th>Appointment Options</th>    
    </tr>
    <% @appointments.each do |appointment| %>
    <%# Must convert the time to 'local' manually | DateTime is weird%>
    <% if appointment.appointment_date < (Time.now - 14400) %>
        <tr class="passed">
    <% end %>
        <td><%= appointment.user.username %></td>
        <td><%= appointment.appointment_date.strftime("%m/%d/%Y %I:%M %p") %></td>
        <td>
            <%= link_to 'View', patient_appointment_path(appointment.patient, appointment), class: "btn btn-info"%>
            <%= link_to 'Edit', edit_patient_appointment_path(appointment.patient, appointment), class: "btn btn-warning"%>
            <%= link_to 'Delete', patient_appointment_path(appointment.patient, appointment), 
            method: :delete,
            class: "btn btn-danger",
            data: {confirm: 'Are you sure?'}%>
        </td>
    </tr>
    <% end %>
</table>