config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'appointments#index'

  # Route will allow deletion of all expired appointments /w button click
  delete 'appointments/delete_all', to: 'appointments#destroy_all_expired'
  
  # Nested Routes for appointments inside of patients
  # /patients/:id/appointments/new
  # /patients/:id/appointments/:id/edit
  resources :patients do
    resources :appointments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user
    belongs_to :patient
    validates :appointment_date, :presence => true
    
    #scope :user_appointments, where('appointment.user_id = ?', current_user.id)
    scope :expired, -> { where("appointment_date < ?", (Time.now - 14400)) }
    scope :current, -> { where("appointment_date > ?", (Time.now - 14400)) }

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]
  before_action :find_patient, only: [:show, :edit, :new, :create]
  
  def index
    @appointments = Appointment.order(:appointment_date)
    @expired_appointments = Appointment.expired
  end

  #appointment_valid? is in the application controller
  def show
    appointment_valid?
  end

  #appointment_valid? is in the application controller
  def edit
    appointment_valid?
    if !current_user.appointments.include?(@appointment)
      redirect_to patient_path(@patient), alert: "You cannot edit another physician's appointments."
    end
  end

  def new
    if !Patient.exists?(params[:patient_id])
      redirect_to patients_path, alert: "You cannot make an appointment for a non-existent patient."
    else
      @appointments = @patient.appointments.order(:appointment_date)
      @your_appts = Appointment.order(:appointment_date)
      @appointment = Appointment.new(patient_id: params[:patient_id])
    end
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user_id = current_user.id
    @appointment.patient_id = params[:patient_id]

    if @appointment.save
      redirect_to patient_path(@appointment.patient_id), notice: "Appointment for #{@patient.name} created sucessfully."
    else
      @appointments = Appointment.all
      @your_appts = Appointment.order(:appointment_date)
      render 'new'
    end
  end

  
  def update
    if @appointment.update(appointment_params)
      redirect_to patient_appointment_path(@appointment.patient_id, @appointment)
    else
      render 'edit'
    end
  end

  # Custom Route that will delete all 'expired' appointments
  # Usage of a scope method chained with .delete_all
  def destroy_all_expired
    Appointment.expired.delete_all
    redirect_to root_path, notice: "Expired appointments deleted successfully."
  end

  # This will only destroy 1 appt at a time - Only if you are the owner
  def destroy
    if current_user.appointments.include?(@appointment)
      @appointment.destroy
      redirect_to patient_path(@appointment.patient), notice: "Appointment deleted sucessfully."
    else
      redirect_to patient_path(@appointment.patient), alert: "You cannot delete another physician's appointments."
    end
  end


  private
  def appointment_params
    params.require(:appointment).permit(:appointment_date)
  end

  def find_appointment
    @appointment = Appointment.find_by(id: params[:id])
  end

  def find_patient
    @patient = Patient.find_by(id: params[:patient_id])
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%# Form for a new Patient /w Appointment %>
<%# Used in: appointments/new | appointments/edit %>
<%= form_for([patient, appointment]) do |f| %>
    <% if appointment.errors.any? %>
        <% appointment.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

<p><%= f.label :appointment_date, "Appointment Date/Time:"%>
<%= datetime_field("appointment", "appointment_date", min: Date.today) %></p>

<%= f.submit %>
<% end %>

app/views/appointments/_upcoming_appt.html.erb
<%# Form for YOUR Upcoming Appointments %>
<%# Used in: appointments/new | patients/new %>
<h3>Your Upcoming Appointments</h3>
<hr class="style-two">
<table style="width:100%">
    <tr>
        <th>Patient Name</th>
        <th>Appointment Date/Time</th>
    </tr>

    <% appointments.each do |appointment| %>
        <% if current_user.id == appointment.user_id %>       
            <% if appointment.appointment_date > (Time.now - 14400) %>
                <td><p>Patient: <%= link_to "#{appointment.patient.name} (Age:  #{appointment.patient.age.to_s})", appointment.patient %></p></td>
                <td><p>Date/Time: <%= appointment.appointment_date.strftime("%m/%d/%Y %I:%M %p") %> </p></td>
                </tr>
            <% end %>
        <% end %>
    <% end %>
</table>

app/views/appointments/edit.html.erb
<h3>Update <%= @patient.name %>'s Appointment with <%= current_user.username %></h3>
<%# Editing Patient Form %>
<%= render partial: 'form', locals: {appointment: @appointment, patient: @patient}  %>

app/views/appointments/index.html.erb
<%# ================= %>
<%# YOUR APPOINTMENTS %>
<%# ================= %>
<h3>Your Appointments (<%= current_user.appointments.count %>)</h3>
<hr class="style-two">
<table style="width:100%">
    <tr>
        <th>Patient Name</th>
        <th>Appointment Date/Time</th>
        <th>Appointment Options</th>
    </tr>

    <% @appointments.each do |appointment| %>
        <% if current_user.id == appointment.user_id %>
            <%# Must convert the time to 'local' manually | DateTime is weird%>
            <% if appointment.appointment_date < (Time.now - 14400) %>
                <tr class="passed">
            <% end %>
            <td><p>Patient: <%= link_to "#{appointment.patient.name} (Age:  #{appointment.patient.age.to_s})", appointment.patient %></p></td>
            <td><p>Date/Time: <%= appointment.appointment_date.strftime("%m/%d/%Y %I:%M %p") %> </p></td>
            <td>
                <%= link_to 'View', patient_appointment_path(appointment.patient, appointment), class: "btn btn-info"%>
                <%= link_to 'Edit', edit_patient_appointment_path(appointment.patient, appointment), class: "btn btn-warning"%>
                <%= link_to 'Delete', patient_appointment_path(appointment.patient, appointment), 
                method: :delete,
                class: "btn btn-danger",
                data: {confirm: 'Are you sure?'}%>
            </td>
            </tr>
        <% end %>
    <% end %>
</table>


<%# ================ %>
<%# ALL APPOINTMENTS %>
<%# ================ %>
<h3>All Appointments (<%= Appointment.all.count %>)</h3>
<hr class="style-two">
<table style="width:100%">
    <tr>
        <th>Physician</th>
        <th>Patient</th>
        <th>Appointment Date/Time</th>
        <th>Appointment Options</th>
    </tr>
  <% @appointments.each do |appointment| %>
  <%# Must convert the time to 'local' manually | DateTime is weird%>
   <% if appointment.appointment_date < (Time.now - 14400) %>
      <tr class="passed">
   <% end %>
        <td><p>Physician: <%= appointment.user.username %></p></td>
        <td><p>Patient: <%= link_to "#{appointment.patient.name} (Age:  #{appointment.patient.age.to_s})", appointment.patient %></p></td>
        <td><p>Date/Time: <%= appointment.appointment_date.strftime("%m/%d/%Y %I:%M %p") %> </p></td>
        <td>
            <%= link_to 'View', patient_appointment_path(appointment.patient, appointment), class: "btn btn-info"%>
            <%= link_to 'Edit', edit_patient_appointment_path(appointment.patient, appointment), class: "btn btn-warning"%>
        </td>
   </tr>
<% end %>
</table>


<%= link_to "DELETE ALL EXPIRED APPOINTMENTS", appointments_delete_all_path, 
                        method: :delete,
                        class: "btn btn-danger",
                        data: {confirm: 'Are you sure?'} %>

app/views/appointments/new.html.erb
<h3>Create A New Appointment For: <%= @appointment.patient.name %></h3>
<hr class="style-two">
<%# New Patient Form %>
<%= render partial: 'form', locals: {appointment: @appointment, patient: @patient}  %>

<hr class="style-two">
<%# Current Patients Upcoming Appoointments %>
<h3><%= @appointment.patient.name %>'s Upcoming Appointments</h3>
<table width="100%">
    <tr>
        <th>Physician</th>
        <th>Appointment Date/Time</th>
    </tr>
    <% @appointments.each do |appointment| %>
        <% if appointment.appointment_date > DateTime.now %>
        <tr>
            <td><%= appointment.user.username %></td>
            <td><%= appointment.appointment_date.strftime("%m/%d/%Y %I:%M %p") %></td>
        </tr>
        <% end %>
    <% end %>
</table>

<%# Form to show YOUR upcoming appointments %>
<%= render partial: 'upcoming_appt', locals: {appointments: @your_appts} %>

app/views/appointments/show.html.erb
<%# Appointment Information Page /w appointment options%>
<h3>Appointment Information</h3>
<hr class="style-two">
<table style="width:100%">
    <tr>
        <th>Patient Name</th>
        <th>Age</th>
        <th>Appointment Date/Time</th>
        <th>Appointment Options</th>
    </tr>
    <tr>
        <td><%= link_to  @patient.name, patient_path(@patient) %></td>
        <td><%= @patient.age %></td>
        <td><%= @appointment.appointment_date.strftime("%m/%d/%Y %I:%M %p") %></td>
        <td>
            <%= link_to 'Edit', edit_patient_appointment_path(@patient, @appointment), class: "btn btn-warning"%>
            <%= link_to 'Delete', patient_appointment_path(@patient, @appointment), 
            method: :delete,
            class: "btn btn-danger",
            data: {confirm: 'Are you sure?'}%>
        </td>
    </tr>
</table>