config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  root to: 'appointments#index'

  # Route will allow deletion of all expired appointments /w button click
  delete 'appointments/delete_all', to: 'appointments#destroy_all_expired'
  
  # Nested Routes for appointments inside of patients
  # /patients/:id/appointments/new
  # /patients/:id/appointments/:id/edit
  resources :patients do
    resources :appointments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <%= link_to 'Home', root_path, :class => "navbar-brand" %>
        <% if !user_signed_in? %>
        <ul class="navbar-nav mr-auto">
            <li><%= link_to 'Sign Up', new_user_registration_path, :class => "navbar-brand" %></li>
            <li><%= link_to 'Login', new_user_session_path, :class => "navbar-brand" %></li>
        </ul>
        <% else %>
        <ul class="navbar-nav mr-auto">
            <li><%= link_to 'Patients', patients_path, :class => "navbar-brand" %></li>
            <li><%= link_to 'Create Patient', new_patient_path, :class => "navbar-brand" %></li>
            <li><%= link_to 'Create Appointment', patients_path, :class => "navbar-brand" %></li>
        </ul>
            <%= link_to "Hello, #{current_user.username}", root_path, :class => "navbar-brand" %>
            <%= link_to 'Logout',  destroy_user_session_path, method: 'delete', :class => "navbar-brand"%>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Appointment Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%=  render 'layouts/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>